FROM ros:humble

# use bash
SHELL ["/bin/bash", "-c"]

# install utilities 
RUN apt update && apt upgrade -y && \
    apt install -y vim nano git wget curl \
    iputils-ping net-tools openssh-server pip


# copy PX4 repository
# COPY PX4-Autopilot /root/PX4-Autopilot

# # Install PX4
# WORKDIR /root
# RUN bash ./PX4-Autopilot/Tools/setup/ubuntu.sh
# WORKDIR /root/PX4-Autopilot/
# RUN make px4_sitl

# debian non interactive
ENV DEBIAN_FRONTEND=noninteractive

# Clone px4
WORKDIR /root
RUN git clone --branch release/1.14 https://github.com/PX4/PX4-Autopilot.git --recursive
WORKDIR /root/PX4-Autopilot
RUN bash ./Tools/setup/ubuntu.sh
RUN make px4_sitl

# python dependencies
RUN pip install --user -U empy==3.3.4 pyros-genmsg setuptools==70.0.0

# setup micro XRCE-DDS Agent & Client
WORKDIR /root
RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git
WORKDIR /root/Micro-XRCE-DDS-Agent
RUN mkdir build
WORKDIR /root/Micro-XRCE-DDS-Agent/build
RUN cmake ..
RUN make
RUN make install
RUN ldconfig /usr/local/lib



# build ROS2 workspace

WORKDIR /root
RUN mkdir -p ~/ws_sensor_combined/src/
WORKDIR /root/ws_sensor_combined/src/
RUN git clone --branch release/1.14 https://github.com/PX4/px4_msgs.git
RUN git clone --branch release/v1.14 https://github.com/PX4/px4_ros_com.git
WORKDIR /root/ws_sensor_combined/
RUN source /opt/ros/humble/setup.bash && colcon build --symlink-install

RUN apt install libnvidia-gl-535 -y





# install ros-humble-ros-gz

RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
RUN apt-get update
RUN apt update && apt install -y ros-humble-ros-gzgarden*

RUN apt install python3-pip -y
RUN pip3 install --upgrade scipy

# put navigation libs px4

# WORKDIR /root/ws_sensor_combined/src/
# RUN git clone --recursive https://github.com/Auterion/px4-ros2-interface-lib
# WORKDIR /root/ws_sensor_combined/
# RUN source /opt/ros/humble/setup.bash && colcon build --symlink-install
RUN apt install ros-humble-depth-image-proc -y
# # set ros_domain_id to 33 to avoid conflicts with other ros2 networks
ENV ROS_DOMAIN_ID=33