FROM ros:humble

ARG PX4_VERSION=1.15

# use bash
SHELL ["/bin/bash", "-c"]

# install utilities 
RUN apt update && apt upgrade -y && \
    apt install -y vim nano git wget curl \
    iputils-ping net-tools openssh-server pip


# copy PX4 repository
# COPY PX4-Autopilot /root/PX4-Autopilot

# # Install PX4
# WORKDIR /root
# RUN bash ./PX4-Autopilot/Tools/setup/ubuntu.sh
# WORKDIR /root/PX4-Autopilot/
# RUN make px4_sitl1.14

# debian non interactive
ENV DEBIAN_FRONTEND=noninteractive

# Clone px4
WORKDIR /root
RUN git clone --recursive --branch release/${PX4_VERSION} https://github.com/PX4/PX4-Autopilot.git
WORKDIR /root/PX4-Autopilot
RUN bash ./Tools/setup/ubuntu.sh
RUN make px4_sitl

# python dependencies
RUN pip install --user -U empy==3.3.4 pyros-genmsg setuptools==70.0.0

# setup micro XRCE-DDS Agent & Client
WORKDIR /root
RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git
WORKDIR /root/Micro-XRCE-DDS-Agent
RUN mkdir build
WORKDIR /root/Micro-XRCE-DDS-Agent/build
RUN cmake ..
RUN make
RUN make install
RUN ldconfig /usr/local/lib



# build ROS2 workspace

WORKDIR /root
RUN mkdir -p ~/ws_sensor_combined/src/
WORKDIR /root/ws_sensor_combined/src/
RUN git clone --branch release/${PX4_VERSION} https://github.com/PX4/px4_msgs.git
RUN git clone --branch release/${PX4_VERSION} https://github.com/PX4/px4_ros_com.git
WORKDIR /root/ws_sensor_combined/
RUN source /opt/ros/humble/setup.bash && colcon build --symlink-install

# install ros-humble-ros-gz

RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
RUN apt-get update && apt install gz-garden

RUN apt install python3-pip -y
RUN pip3 install --upgrade scipy

RUN apt update && apt install ros-humble-depth-image-proc -y
# set ros_domain_id to 33 to avoid conflicts with other ros2 networks
ENV ROS_DOMAIN_ID=33